<?xml version="1.0" encoding="utf-8"?>
<Database Name="EaGUI" EntityNamespace="GUI.Model" ContextNamespace="GUI" Class="DB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=EaGUI;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EaGUIConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataElements" Member="DataElements">
    <Type Name="DataElement">
      <Column Name="DataElement_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DataElement_DataGroup_Element" Member="DataGroup_Elements" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="DataGroup_Element" />
      <Association Name="DataElement_Job_DataElement" Member="Job_DataElements" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="Job_DataElement" />
      <Association Name="DataElement_Problem_DataElement" Member="Problem_DataElements" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="Problem_DataElement" />
      <Association Name="DataSource_DataElement" Member="DataSource" ThisKey="Source_Id" OtherKey="DataSource_Id" Type="DataSource" IsForeignKey="true" />
      <Association Name="DataType_DataElement" Member="DataType" ThisKey="DataType_Id" OtherKey="DataType_Id" Type="DataType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Problems" Member="Problems">
    <Type Name="Problem">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Problem_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Problem_Option" Member="Options" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Option" />
      <Association Name="Problem_Problem_DataElement" Member="Problem_DataElements" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Problem_DataElement" />
      <Association Name="Problem_Job" Member="Jobs" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Job" />
    </Type>
  </Table>
  <Table Name="dbo.DataGroup_Element" Member="DataGroup_Elements">
    <Type Name="DataGroup_Element">
      <Column Name="DataGroup_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataElement_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DataElement_DataGroup_Element" Member="DataElement" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="DataElement" IsForeignKey="true" />
      <Association Name="DataGroup_DataGroup_Element" Member="DataGroup" ThisKey="DataGroup_Id" OtherKey="DataGroup_Id" Type="DataGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataGroups" Member="DataGroups">
    <Type Name="DataGroup">
      <Column Name="DataGroup_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="DataGroup_DataGroup_Element" Member="DataGroup_Elements" ThisKey="DataGroup_Id" OtherKey="DataGroup_Id" Type="DataGroup_Element" />
    </Type>
  </Table>
  <Table Name="dbo.DataSources" Member="DataSources">
    <Type Name="DataSource">
      <Column Name="DataSource_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="DataSource_DataElement" Member="DataElements" ThisKey="DataSource_Id" OtherKey="Source_Id" Type="DataElement" />
    </Type>
  </Table>
  <Table Name="dbo.DataTypes" Member="DataTypes">
    <Type Name="DataType">
      <Column Name="DataType_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="DataType_DataElement" Member="DataElements" ThisKey="DataType_Id" OtherKey="DataType_Id" Type="DataElement" />
      <Association Name="DataType_Option" Member="Options" ThisKey="DataType_Id" OtherKey="DataType_Id" Type="Option" />
    </Type>
  </Table>
  <Table Name="dbo.Job_DataElement" Member="Job_DataElements">
    <Type Name="Job_DataElement">
      <Column Name="Job_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataElement_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DataElement_Job_DataElement" Member="DataElement" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="DataElement" IsForeignKey="true" />
      <Association Name="Job_Job_DataElement" Member="Job" ThisKey="Job_Id" OtherKey="Job_Id" Type="Job" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Job_Option" Member="Job_Options">
    <Type Name="Job_Option">
      <Column Name="Job_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Option_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="String_Value" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Float_Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Bit_Value" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Option_Job_Option" Member="Option" ThisKey="Option_Id" OtherKey="Option_Id" Type="Option" IsForeignKey="true" />
      <Association Name="Job_Job_Option" Member="Job" ThisKey="Job_Id" OtherKey="Job_Id" Type="Job" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobHistory" Member="JobHistories">
    <Type Name="JobHistory">
      <Column Name="JobHistory_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Job_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Job_JobHistory" Member="Job" ThisKey="Job_Id" OtherKey="Job_Id" Type="Job" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OptionCategories" Member="OptionCategories">
    <Type Name="OptionCategory">
      <Column Name="OptionCategory_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="OptionCategory_Option" Member="Options" ThisKey="OptionCategory_Id" OtherKey="OptionCategory_Id" Type="Option" />
    </Type>
  </Table>
  <Table Name="dbo.Options" Member="Options">
    <Type Name="Option">
      <Column Name="Option_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptionCategory_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Problem_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MinValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AllowMultipleSelection" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Option_Job_Option" Member="Job_Options" ThisKey="Option_Id" OtherKey="Option_Id" Type="Job_Option" />
      <Association Name="OptionCategory_Option" Member="OptionCategory" ThisKey="OptionCategory_Id" OtherKey="OptionCategory_Id" Type="OptionCategory" IsForeignKey="true" />
      <Association Name="DataType_Option" Member="DataType" ThisKey="DataType_Id" OtherKey="DataType_Id" Type="DataType" IsForeignKey="true" />
      <Association Name="Problem_Option" Member="Problem" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Problem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Problem_DataElement" Member="Problem_DataElements">
    <Type Name="Problem_DataElement">
      <Column Name="Problem_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataElement_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DataElement_Problem_DataElement" Member="DataElement" ThisKey="DataElement_Id" OtherKey="DataElement_Id" Type="DataElement" IsForeignKey="true" />
      <Association Name="Problem_Problem_DataElement" Member="Problem" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Problem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jobs" Member="Jobs">
    <Type Name="Job">
      <Column Name="Job_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsTemplate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Problem_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Stats" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Parameters" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Job_Job_DataElement" Member="Job_DataElements" ThisKey="Job_Id" OtherKey="Job_Id" Type="Job_DataElement" />
      <Association Name="Job_Job_Option" Member="Job_Options" ThisKey="Job_Id" OtherKey="Job_Id" Type="Job_Option" />
      <Association Name="Job_JobHistory" Member="JobHistories" ThisKey="Job_Id" OtherKey="Job_Id" Type="JobHistory" />
      <Association Name="Problem_Job" Member="Problem" ThisKey="Problem_Id" OtherKey="Problem_Id" Type="Problem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>